### ISSUE TITLE
How many lumens? It needs to be a little brighter. I was thinking up it to like 5000.

### ISSUE THREAD

**Issue by liu7d7** [olliem5/lumen#1]
title

**Comment by olliem5** [comment]
I'm thinking about 6000. Not too sure though.

**Comment by ghost** [comment]
https://www.amazon.com/Feit-Electric-C20000-5K-LED/dp/B07XCYKP9K
20,000 lumens (fullbright @ 20k = no eyes👍)

**Comment by yagel15637** [comment]
what is a lumen

**Comment by ghost** [comment]
A unit of light emitted from an object....

**Comment by ghost** [comment]
fullbright irl ez
