### ISSUE TITLE
stupid

### ISSUE THREAD

**Issue by Drakesdrs** [olliem5/lumen#3]
worst client ever

**Comment by y4ndex1** [comment]
you cant give out opinions when you don't even know how to build wurstplustwo

**Comment by yagel15637** [comment]
> worst client ever

@Drakesdrs this client is a WIP, it does not have even 1 ready module yet, and while I'm sure @olliem5 appreciates feedback, please wait until there is something to give feedback on. @olliem5 can you close this?

**Comment by olliem5** [comment]
This was a very useful issue, thanks for the feedback! I’m now going to proceed to discontinue the client, along with ending my life because I have nothing left to live for.

**Comment by Drakesdrs** [comment]
> 
> 
> you cant give out opinions when you don't even know how to build wurstplustwo

are you retarded

**Comment by yagel15637** [comment]
you are very slow and extremely funny.
